# config/cable.yml
development:
  adapter: async

test:
  adapter: test

# üõ†Ô∏è CAMBIO CLAVE:
# Usamos "async" para que los mensajes viajen por la Memoria RAM.
# Esto evita el Error 500 porque no intenta escribir en la base de datos.
production:
  adapter: async
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: powergym_production