# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gym_control_development
  username: jorch
  host: /var/run/postgresql

test:
  <<: *default
  database: gym_control_test
  username: jorch
  host: /var/run/postgresql

# En producciÃ³n usa DATABASE_URL (recomendado).
# Ejemplo: postgres://user:pass@host:5432/gym_control_production
production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

