# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gym_control_development
  username: jorch
  host: /var/run/postgresql

test:
  <<: *default
  database: gym_control_test
  username: jorch
  host: /var/run/postgresql

# En producción definimos TRES roles de conexión:
# - primary  -> tu app (ActiveRecord)
# - cable    -> Solid Cable (ActionCable)
# - queue    -> Solid Queue (jobs)
production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    <<: *default
    url: <%= ENV.fetch("CABLE_DATABASE_URL", ENV["DATABASE_URL"]) %>

  queue:
    <<: *default
    url: <%= ENV.fetch("QUEUE_DATABASE_URL", ENV["DATABASE_URL"]) %>
